spring:
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017/susano?authMechanism=SCRAM-SHA-1&authSource=admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      database: 0
